version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - db
    networks:
      - custom_network

  db:
    build: ./db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
    networks:
      - custom_network

networks:
  custom_network:
   driver: bridge